#!/bin/bash
set -euo pipefail

if [ "$#" -lt 1 ]; then
    TICKET_ID=$(ticket);
else
    TICKET_ID=$1
fi

if [ -z "$JIRA_URL" ]; then
    echo "JIRA_URL env variable expected"
    exit 1
fi
if [ -z "$JIRA_USERNAME" ]; then
    echo "JIRA_USERNAME env variable expected"
    exit 1
fi
if [ -z "$JIRA_API_TOKEN" ]; then
    echo "JIRA_API_TOKEN env variable expected"
    exit 1
fi
API_ENDPOINT="/rest/api/2/issue/${TICKET_ID}?fields\=summary,description,assignee,reporter,priority,status,issuetype,created,updated"

# Fetching ticket details
RESPONSE=$(curl -s -u "$JIRA_USERNAME:$JIRA_API_TOKEN" -X GET "$JIRA_URL$API_ENDPOINT" -H "Accept: application/json")

# Check if the response is successful
if [[ $(echo "$RESPONSE" | jq -r '.errorMessages | length') -ne 0 ]]; then
    echo "Error: $(echo "$RESPONSE" | jq -r '.errorMessages | .[0]')" >&2
    exit 2
fi

# Extracting the ticket OUTPUT
OUTPUT=$(echo "$RESPONSE" |
    jq '
{key: .key,
 summary: .fields.summary,
 type: .fields.issuetype.name,
 created: .fields.created,
 updated: .fields.updated,
 description: .fields.description,
 reporter: {
   displayName: .fields.reporter.displayName,
   email: .fields.reporter.emailAddress
 },
 assignee: {
  displayName: .fields.assignee.displayName,
  email: .fields.assignee.emailAddress
 },
 priority: .fields.priority.name,
 status: .fields.status.name
}
'
)

echo $OUTPUT
