#!/bin/bash

TICKET_ID=""
OPTION=""

usage() {
    echo "Usage: $0 [TICKET_ID] [--option]"
    echo "Example: $0 12345 --all"
}

for arg in "$@"; do
    if [[ $arg == --* ]]; then
        OPTION="$arg"
    elif [[ -z "$TICKET_ID" ]]; then
        TICKET_ID="$arg"
    else
        echo "Too many arguments provided."
        usage
        exit 1
    fi
done

if [[ $OPTION == "--help" ]]; then
    usage
    exit 0
fi

# Output results
TICKET_ID=${TICKET_ID:-$(ticket)}
OPTION=${OPTION}

if [ -z "$JIRA_URL" ]; then
    echo "JIRA_URL env variable expected"
    exit 1
fi
if [ -z "$JIRA_USERNAME" ]; then
    echo "JIRA_USERNAME env variable expected"
    exit 1
fi

JIRA_API_TOKEN=$(auth tokens/jira)
API_ENDPOINT="/rest/api/2/issue/${TICKET_ID}?fields\=summary,description,assignee,reporter,priority,status,issuetype,created,updated"

# Fetching ticket details
RESPONSE=$(curl -s -u "$JIRA_USERNAME:$JIRA_API_TOKEN" -X GET "$JIRA_URL$API_ENDPOINT" -H "Accept: application/json")

# Check if the response is successful
if [[ $(echo "$RESPONSE" | jq -r '.errorMessages | length') -ne 0 ]]; then
    echo "Error: $(echo "$RESPONSE" | jq -r '.errorMessages | .[0]')" >&2
    exit 2
fi

if [[ $OPTION == "--all" ]]; then
    OUTPUT=$RESPONSE
else
    OUTPUT=$(echo "$RESPONSE" |
        jq '
    {key: .key,
     summary: .fields.summary,
     type: .fields.issuetype.name,
     created: .fields.created,
     updated: .fields.updated,
     description: .fields.description,
     reporter: {
       displayName: .fields.reporter.displayName,
       email: .fields.reporter.emailAddress
     },
     assignee: {
      displayName: .fields.assignee.displayName,
      email: .fields.assignee.emailAddress
     },
     priority: .fields.priority.name,
     status: .fields.status.name
    }
    '
    )
fi

echo $OUTPUT
