#!/bin/zsh
set -euo pipefail

FALLBACK_FILENAME=~/ticket_id
FILENAME=${~TICKET_FILE:-${~FALLBACK_FILENAME}}

if [ ! -f ${~FILENAME} ]; then
  echo "No ticket set at $FILENAME. Use set_ticket <ticket> before" >&2
  exit 2
fi

# Check if the file is empty
if [ ! -s "${~FILENAME}" ]; then
  echo "No ticket set at $FILENAME. Use set_ticket <ticket> before" >&2
  exit 3
fi

cat ${~FILENAME}
